version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      kotlin-ecosystem:
        patterns:
          - "org.jetbrains.kotlin*"
          - "org.jetbrains.kotlinx*"
      jetbrains-compose:
        patterns:
          - "org.jetbrains.compose*"
          - "org.jetbrains.androidx*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
