include(":common:common")
include(":common:common_test")
include(":common:common_test_ui")

include(":base_android")
include(":base_camera")
include(":base_file")
include(":base_firebase")
include(":base_persistence")
include(":base_work_manager")
include(":base_cache")

include(":ui:ui_common")
include(":ui:ui_permissions")
include(":ui:ui_doorbell_list")
include(":ui:ui_image_list")
include(":ui:ui_image_details")
include(":navigation")

include(":app:app_kodein")
include(":app:app_koin")
include(":app:app_singleton")
include(":app:app_toothpick")

include(":app:dagger:dagger_common")
include(":app:dagger:dagger_permissions")
include(":app:dagger:dagger_doorbell_list")
include(":app:dagger:dagger_image_list")
include(":app:dagger:dagger_image_details")
include(":app:dagger:app_dagger")
