name: actionsEmulator29

on: [push]

jobs:

  jobEmulator29:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'
      - run: bash ./gradlew :setupAndroidCmdlineTools --stacktrace
      - run: bash ./gradlew ciEmulator29 --stacktrace
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: screenshots
          path: build/screenshots/
