name: actionsAfterPush

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2.0.0

      - name: ciBuildApp
        run: bash ./gradlew ciBuildApp --stacktrace

      - uses: actions/upload-artifact@v1
        with:
          name: apk
          path: build/apk/

      - uses: actions/upload-artifact@v1
        with:
          name: jacoco
          path: build/reports/jacoco/

      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: screenshots
          path: build/screenshots/
