name: actionsBuildApp

on: [ push ]

jobs:

  jobLint:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'
      - run: bash ./gradlew ciLint --stacktrace


  jobUnitTest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'
      - run: bash ./gradlew ciUnitTest --stacktrace
      - uses: actions/upload-artifact@v1
        with:
          name: jacoco
          path: build/reports/kover/


  jobBuildApp:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'
      - run: bash ./gradlew ciBuildApp --stacktrace
      - uses: actions/upload-artifact@v2
        with:
          name: apk
          path: build/apk/
