name: actionsEmulator

on: [ push ]

jobs:

  Emulator:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest ]
        emulator-varsion: [ 30, 31, 32, 33 ]
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        if: ${{ matrix.os != 'self-hosted' }}
        with:
          distribution: 'temurin'
          java-version: '11'

      - run: bash ./gradlew :setupAndroidCmdlineTools :setupAndroidSDK --stacktrace
        working-directory: ./android_sdk

      - run: bash ./gradlew ciEmulator${{ matrix.emulator-varsion }} --stacktrace

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: screenshots
          path: ${{ github.workspace }}/**/screenshot/debug/**/*.png

      - run: bash ./gradlew :killAndroidEmulator :deleteAndroidEmulator --stacktrace
        working-directory: ./android_sdk
        if: always()
