name: actionsAfterPush

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2.0.0

      - name: ciRunAndroidEmulator
        run: bash ./gradlew ciRunAndroidEmulator --stacktrace

      - name: ciBuildApp
        run: bash ./gradlew ciBuildApp --stacktrace

      - name: waitAndroidEmulator
        run: bash ./gradlew waitAndroidEmulator --stacktrace

      - name: connectedAndroidTest
        run: bash ./gradlew connectedAndroidTest --stacktrace

      - name: Prepare Artifacts
        run: bash ./gradlew copyApkArtifacts moveScreenshotsFromDevices --stacktrace

      - name: killAndroidEmulator
        run: bash ./gradlew killAndroidEmulator --stacktrace

      - uses: actions/upload-artifact@v1
        with:
          name: apk
          path: build/artifacts/outputs/apk/

      - uses: actions/upload-artifact@v1
        with:
          name: screenshots
          path: build/artifacts/screenshots/
