name: actionsEmulator

on: [ push ]

jobs:

  Emulator:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest ]
        emulator-varsion: [ 23, 28, 29, 30, 31, 32 ]
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'
      - run: bash ./gradlew :setupAndroidCmdlineTools --stacktrace
      - run: bash ./gradlew ciEmulator${{ matrix.emulator-varsion }} --stacktrace
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: screenshots
          path: build/screenshots/
