name: actionsBuildApp

on: [push]

jobs:

  jobLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'
      - run: bash ./gradlew :setupAndroidCmdlineTools --stacktrace
      - run: bash ./gradlew ciLint --stacktrace


  jobUnitTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'
      - run: bash ./gradlew :setupAndroidCmdlineTools --stacktrace
      - run: bash ./gradlew ciUnitTest --stacktrace
      - uses: actions/upload-artifact@v1
        with:
          name: jacoco
          path: build/reports/jacoco/


  jobBuildApp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'
      - run: bash ./gradlew :setupAndroidCmdlineTools --stacktrace
      - run: bash ./gradlew ciBuildApp --stacktrace
      - uses: actions/upload-artifact@v1
        with:
          name: apk
          path: build/apk/
