name: actionsEmulator30

on: [push]

jobs:

  jobEmulator30:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'
      - run: bash ./gradlew :setupAndroidCmdlineTools --stacktrace
      - name: ciEmulator30
        run: bash ./gradlew ciEmulator30 --stacktrace
        continue-on-error: true
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: screenshots
          path: build/screenshots/
