name: actionsBuildApp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  JAVA_VERSION: 21
  JAVA_DISTRIBUTION: 'temurin'

jobs:


  jobLint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew wrapper --gradle-version latest --stacktrace
      - run: ./gradlew wrapper --gradle-version latest --stacktrace
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Update Gradle wrapper

      - run: ./gradlew ktlintFormat --stacktrace
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Ktlint format

      - run: ./gradlew ciLint --stacktrace



  jobUnitTest:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v5

      - uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew ciUnitTest --stacktrace



  jobRecordScreenshots:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew ciRecordScreenshots --stacktrace

      - uses: stefanzweifel/git-auto-commit-action@v6



  jobBuildApp:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v5

      - uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew ciBuildApp --stacktrace



  jobEmulatorMatrixSetup:
    runs-on: ubuntu-latest
    outputs:
      emulator_jobs_matrix: ${{ steps.dataStep.outputs.emulator_jobs_matrix }}
    steps:

      - uses: actions/checkout@v5

      - uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew ciEmulatorJobsMatrixSetup --stacktrace

      - id: dataStep
        run: echo "emulator_jobs_matrix=$(jq -c . < ./build/emulator_jobs_matrix.json)" >> $GITHUB_OUTPUT



  Emulator:
    needs: jobEmulatorMatrixSetup
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.variants.experimental }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.jobEmulatorMatrixSetup.outputs.emulator_jobs_matrix) }}
    steps:

      - uses: actions/checkout@v5

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew ciSdkManagerLicenses --stacktrace

      - run: ./gradlew ${{ matrix.variants.gradle_tasks }} --stacktrace
