name: actionsBuildApp

on: [push]

jobs:

  jobBuildApp:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - run: bash ./gradlew :setupAndroidCmdlineTools --stacktrace
      - run: bash ./gradlew ciBuildApp --stacktrace
      - uses: actions/upload-artifact@v1
        with:
          name: apk
          path: build/apk/
      - uses: actions/upload-artifact@v1
        with:
          name: jacoco
          path: build/reports/jacoco/
